export const ADDTODO = 'ADDTODO';
export const CHANGEFILTER = 'CHANGEFILTER';
export const REMOVECOMPLETED = 'REMOVECOMPLETED';
export const SETALLTODOS = 'SETALLTODOS';
export const COMPLETETODO = 'COMPLETEDTODO';
export const REMOVETODO = 'REMOVETODO';